name = "test"
main = "src/index.js"
compatibility_date = "2024-03-25"

# 配置 D1 数据库绑定
# 当你在 CF 控制台创建好 D1 后，使用下方的 ID 替换 database_id 即可部署
[[d1_databases]]
binding = "DB"
database_name = "CloudflareTempMail-db"
database_id = "80bc873f-0e11-4f25-83da-8f529f1dd7bb"
preview_database_id = "DB"

[vars]
# 访问网页管理后台的密码，默认 123456
ADMIN_PASSWORD = "123456"
